### ISSUE TITLE
Running on latest pyxel release

### ISSUE THREAD

**Issue by alderven** [danmacnaughtan/pyxel-raycast#1]
I'm trying to run your script on latest `pyxel` version (1.4.3) and getting following error:

```
  File "main.py", line 372, in window
    return pyxel._app._window
AttributeError: 'Module' object has no attribute '_app'
```

Is there any chance to make it compatible with latest `pyxel`?

**Comment by danmacnaughtan** [comment]
The project has been updated to use the latest version of pyxel (1.4.3), thanks!
