### ISSUE TITLE
Compress GIF file

### ISSUE THREAD

**Issue by alderven** [danmacnaughtan/pyxel-raycast#3]
Your [gif](https://github.com/danmacnaughtan/pyxel-raycast/blob/master/example.gif) file size is `25 MB`.
You can use compressed version which size is `2.5 MB`:

![example_compressed](https://user-images.githubusercontent.com/21060932/145664725-c7e5aa22-4a5a-4810-9ee8-b9821c74173d.gif)

**Comment by danmacnaughtan** [comment]
Hey thanks! TIL about gif file optimization. I've updated my example gif as per your suggestion.
